### ISSUE TITLE
service->running not working centos7

### ISSUE THREAD

**Issue by mlosapio** [MetaCenterCloudPuppet/cesnet-hbase#2]
The service type not actually detecting an issue on CentOS 7. 

My theory is that since systemd isn't returning the correct value, is causing puppet not to work as expected. 

```[root@]# /etc/init.d/hbase-regionserver status
hbase-regionserver is not running.
[root@]# echo $?
1
```
```
[root@]# systemctl status hbase-regionserver
● hbase-regionserver.service - LSB: Hadoop HBase regionserver daemon
   Loaded: loaded (/etc/rc.d/init.d/hbase-regionserver; bad; vendor preset: disabled)
   Active: active (exited) since Sat 2017-03-04 08:17:33 UTC; 2 weeks 2 days ago
     Docs: man:systemd-sysv-generator(8)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
[root@]# echo $?
0
```

**Comment by mlosapio** [comment]
When I explicitly update the service as the provider => redhat, it functions as expected. 

```
class hbase::regionserver::service {
  service { $hbase::daemons['regionserver']:
    ensure => running,
    enable => true,
    provider => redhat,
  }
}
```

**Comment by valtri** [comment]
Problem is the startup script from Cloudera. As the command line for launching regionserver is quite long, this won't detect HBase regionserver runnging process correctly:

    ps -fp $pid | grep $pid | grep regionserver

Interesting is, after manual restart of the puppet agent, regionserver process is detected correctly - probably something with different terminal configuration (used for the puppet agent) during boot.

The fix is probably up to Cloudera. I'm not sure about the best way, probably adding some '-ww' argument to 'ps' would work...?

**Comment by valtri** [comment]
The pull request has been merged. It doesn't help with the issue I can reproduce though, this issue in CentOS 7 is probably different... does the last version at github helps in CentOS?

**Comment by mlosapio** [comment]
Yep this'll do. 

Thanks for the speedy help.
